package com.mlay.animedownloader;
import android.content.*;import android.content.ContentValues;import android.os.*;import android.provider.MediaStore;import java.io.*;import java.net.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicLong;
public final class DownloadEngine{
 public interface Listener{void progress(long done,long total,long bps);void state(String s);void error(String e);}
 private final ExecutorService episodes=Executors.newFixedThreadPool(3);
 public void enqueue(Context ctx,String url,String anime,String lang,String file,Listener l){episodes.submit(()->download(ctx,url,anime,lang,file,l));}
 private void download(Context ctx,String url,String anime,String lang,String file,Listener l){try{l.state("Connexion");HttpURLConnection h=(HttpURLConnection)new URL(url).openConnection();h.setRequestMethod("HEAD");h.setConnectTimeout(15000);h.connect();long len=h.getContentLengthLong();boolean ranges="bytes".equalsIgnoreCase(h.getHeaderField("Accept-Ranges"));h.disconnect();if(len<=0||!ranges){single(ctx,url,anime,lang,file,l,len);return;}File dir=new File(ctx.getCacheDir(),"kaze_parts");dir.mkdirs();File[] parts=new File[4];ExecutorService pool=Executors.newFixedThreadPool(4);CountDownLatch latch=new CountDownLatch(4);AtomicLong done=new AtomicLong();long started=System.currentTimeMillis();for(int i=0;i<4;i++){final int n=i;long start=len*i/4,end=(i==3?len-1:len*(i+1)/4-1);parts[i]=new File(dir,file+"."+i+".part");pool.submit(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestProperty("Range","bytes="+start+"-"+end);try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(parts[n])){byte[] b=new byte[65536];int z;while((z=in.read(b))!=-1){out.write(b,0,z);long d=done.addAndGet(z),ms=Math.max(1,System.currentTimeMillis()-started);l.progress(d,len,d*1000/ms);}}}catch(Exception e){l.error(e.getMessage());}finally{latch.countDown();}});}l.state("Téléchargement • 4 connexions");latch.await();pool.shutdown();saveParts(ctx,parts,anime,lang,file);for(File p:parts)p.delete();l.state("Terminé");}catch(Exception e){l.error(e.getMessage()==null?"Erreur de téléchargement":e.getMessage());}}
 private void single(Context ctx,String url,String anime,String lang,String file,Listener l,long total)throws Exception{l.state("Téléchargement • 1 connexion");HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();long len=total>0?total:c.getContentLengthLong();File tmp=new File(ctx.getCacheDir(),file+".part");long done=0,start=System.currentTimeMillis();try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(tmp)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1){out.write(b,0,n);done+=n;l.progress(done,len,done*1000/Math.max(1,System.currentTimeMillis()-start));}}saveFile(ctx,tmp,anime,lang,file);tmp.delete();l.state("Terminé");}
 private void saveParts(Context ctx,File[] ps,String anime,String lang,String file)throws Exception{ContentValues v=values(anime,lang,file);android.net.Uri u=ctx.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);try(OutputStream out=ctx.getContentResolver().openOutputStream(u)){byte[] b=new byte[65536];for(File p:ps)try(InputStream in=new FileInputStream(p)){int n;while((n=in.read(b))!=-1)out.write(b,0,n);}}}
 private void saveFile(Context ctx,File src,String anime,String lang,String file)throws Exception{ContentValues v=values(anime,lang,file);android.net.Uri u=ctx.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);try(InputStream in=new FileInputStream(src);OutputStream out=ctx.getContentResolver().openOutputStream(u)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1)out.write(b,0,n);}}
 private ContentValues values(String anime,String lang,String file){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,file);v.put(MediaStore.Downloads.MIME_TYPE,"video/mp4");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/KAZE/"+clean(anime)+"/"+lang);return v;}private String clean(String s){return s.replaceAll("[\\\\/:*?\"<>|]","_");}
}