package com.mlay.animedownloader;
import android.content.*;import android.os.*;import android.provider.MediaStore;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
public final class HlsEngine{
 public interface Listener{void progress(long done,long total,long bps);void state(String s);void error(String e);}
 public void download(Context ctx,String url,String anime,String lang,String file,Map<String,String> headers,String preferred,Listener l){
  ExecutorService pool=null;try{
   l.state("Analyse HLS");String master=text(url,headers);if(master.contains("#EXT-X-KEY")&&!master.contains("METHOD=NONE"))throw new IOException("Flux HLS chiffré non pris en charge");
   String mediaUrl=url;
   if(master.contains("#EXT-X-STREAM-INF")){List<Variant> vs=variants(url,master);if(vs.isEmpty())throw new IOException("Aucune variante HLS");Variant pick=pick(vs,preferred);mediaUrl=pick.url;master=text(mediaUrl,headers);if(master.contains("#EXT-X-KEY")&&!master.contains("METHOD=NONE"))throw new IOException("Flux HLS chiffré non pris en charge");}
   if(!master.contains("#EXT-X-ENDLIST"))throw new IOException("Flux HLS live non pris en charge");
   List<String> segs=segments(mediaUrl,master);if(segs.isEmpty())throw new IOException("Aucun segment HLS");
   File dir=new File(ctx.getCacheDir(),"kaze_hls_"+System.nanoTime());if(!dir.mkdirs())throw new IOException("Cache HLS indisponible");
   File[] parts=new File[segs.size()];AtomicLong done=new AtomicLong();AtomicReference<Throwable> fail=new AtomicReference<>();long start=System.currentTimeMillis();pool=Executors.newFixedThreadPool(4);List<Future<?>> fs=new ArrayList<>();l.state("Téléchargement HLS • 4 connexions");
   for(int i=0;i<segs.size();i++){final int n=i;parts[i]=new File(dir,String.format(Locale.ROOT,"%06d.part",i));fs.add(pool.submit(()->{try{HttpURLConnection c=open(segs.get(n),headers);int code=c.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(parts[n])){byte[] b=new byte[65536];int z;while((z=in.read(b))!=-1){out.write(b,0,z);long d=done.addAndGet(z);l.progress(d,-1,d*1000/Math.max(1,System.currentTimeMillis()-start));}}c.disconnect();}catch(Throwable e){fail.compareAndSet(null,e);}}));}
   for(Future<?> f:fs)f.get();pool.shutdown();pool=null;if(fail.get()!=null)throw new IOException(msg(fail.get()));
   l.state("Assemblage HLS");save(ctx,parts,anime,lang,file.endsWith(".ts")?file:file+".ts");for(File p:parts)p.delete();dir.delete();l.state("Terminé");
  }catch(Exception e){if(pool!=null)pool.shutdownNow();l.error(msg(e));}
 }
 private String text(String url,Map<String,String> h)throws Exception{HttpURLConnection c=open(url,h);int code=c.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);ByteArrayOutputStream o=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);}c.disconnect();return o.toString("UTF-8");}
 private List<Variant> variants(String base,String m)throws Exception{List<Variant> out=new ArrayList<>();String[] a=m.split("\\r?\\n");for(int i=0;i<a.length;i++)if(a[i].startsWith("#EXT-X-STREAM-INF")){int h=0;String line=a[i];int p=line.indexOf("RESOLUTION=");if(p>=0){String x=line.substring(p+11).split(",")[0];int k=x.indexOf('x');if(k>=0)try{h=Integer.parseInt(x.substring(k+1));}catch(Exception ignored){}}for(int j=i+1;j<a.length;j++)if(!a[j].trim().isEmpty()&&!a[j].startsWith("#")){out.add(new Variant(resolve(base,a[j].trim()),h));break;}}return out;}
 private Variant pick(List<Variant> vs,String pref)throws IOException{int want=0;try{want=Integer.parseInt(pref.replaceAll("\\D",""));}catch(Exception ignored){}if(want>0){for(Variant v:vs)if(v.height==want)return v;throw new IOException("Qualité "+pref+" indisponible pour ce flux");}Variant best=vs.get(0);for(Variant v:vs)if(v.height>best.height)best=v;return best;}
 private List<String> segments(String base,String m)throws Exception{List<String> out=new ArrayList<>();for(String x:m.split("\\r?\\n")){x=x.trim();if(!x.isEmpty()&&!x.startsWith("#"))out.add(resolve(base,x));}return out;}
 private String resolve(String base,String x)throws Exception{return new URL(new URL(base),x).toString();}
 private HttpURLConnection open(String u,Map<String,String> h)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(20000);c.setReadTimeout(30000);if(h!=null)for(Map.Entry<String,String> e:h.entrySet())if(e.getKey()!=null&&e.getValue()!=null&&!e.getKey().equalsIgnoreCase("Host")&&!e.getKey().equalsIgnoreCase("Content-Length"))try{c.setRequestProperty(e.getKey(),e.getValue());}catch(Exception ignored){}return c;}
 private void save(Context ctx,File[] ps,String anime,String lang,String file)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,clean(file));v.put(MediaStore.Downloads.MIME_TYPE,"video/mp2t");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/KAZE/"+clean(anime)+"/"+clean(lang));v.put(MediaStore.Downloads.IS_PENDING,1);android.net.Uri u=ctx.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("Impossible de créer le fichier");try(OutputStream out=ctx.getContentResolver().openOutputStream(u)){byte[] b=new byte[65536];for(File p:ps)try(InputStream in=new FileInputStream(p)){int n;while((n=in.read(b))!=-1)out.write(b,0,n);}}ContentValues done=new ContentValues();done.put(MediaStore.Downloads.IS_PENDING,0);ctx.getContentResolver().update(u,done,null,null);}
 private String clean(String s){return(s==null?"KAZE":s).replaceAll("[\\\\/:*?\"<>|]","_");}private String msg(Throwable e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
 private static final class Variant{final String url;final int height;Variant(String u,int h){url=u;height=h;}}
}