package com.mlay.animedownloader;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.content.*;import android.content.res.ColorStateList;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;import org.json.*;

public class MainActivity extends Activity{
 final int BG=Color.rgb(9,10,16),CARD=Color.rgb(24,26,37),P=Color.rgb(121,82,255),W=Color.WHITE,M=Color.rgb(174,177,195);
 LinearLayout content;EditText query;Handler ui=new Handler(Looper.getMainLooper());ExecutorService net=Executors.newFixedThreadPool(6);Set<Integer> selected=new LinkedHashSet<>();String lang="VOSTFR";
 public void onCreate(Bundle b){super.onCreate(b);home();}
 TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(10,8,10,8);return v;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(W);b.setTextSize(14);b.setMinHeight(56);b.setBackground(bg(P,28));return b;}
 void home(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(18,22,18,50);sc.addView(p);TextView k=t("KAZE",32,W);k.setTypeface(null,1);p.addView(k);p.addView(t("Anime • VF • VOSTFR",14,M));
  LinearLayout bar=new LinearLayout(this);bar.setPadding(0,14,0,10);query=new EditText(this);query.setHint("Rechercher un anime...");query.setHintTextColor(M);query.setTextColor(W);query.setSingleLine();query.setPadding(18,0,18,0);query.setBackground(bg(CARD,28));bar.addView(query,new LinearLayout.LayoutParams(0,58,1));Button go=btn("Chercher");LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-2,58);gp.setMargins(8,0,0,0);bar.addView(go,gp);p.addView(bar);go.setOnClickListener(v->search());query.setOnEditorActionListener((v,a,e)->{search();return true;});
  p.addView(t("Découvrir",24,W));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);p.addView(content);setContentView(sc);trending();}
 void trending(){loading("Chargement...");net.submit(()->{try{JSONArray a=api("query{Page(page:1,perPage:15){media(type:ANIME,sort:TRENDING_DESC,isAdult:false){id title{romaji english} coverImage{large} episodes status seasonYear description(asHtml:false)}}}",null).getJSONObject("data").getJSONObject("Page").getJSONArray("media");ui.post(()->render(a));}catch(Exception e){ui.post(()->loading("Catalogue temporairement indisponible."));}});}
 void search(){String q=query.getText().toString().trim().replaceAll("(?i)\\s+(vf|vostfr)$","").trim();if(q.isEmpty())return;((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(query.getWindowToken(),0);loading("Recherche...");final String z=q;net.submit(()->{try{JSONObject vars=new JSONObject().put("q",z);JSONArray a=api("query($q:String){Page(page:1,perPage:30){media(type:ANIME,search:$q,isAdult:false,sort:SEARCH_MATCH){id title{romaji english} coverImage{large} episodes status seasonYear description(asHtml:false)}}}",vars).getJSONObject("data").getJSONObject("Page").getJSONArray("media");ui.post(()->render(a));}catch(Exception e){ui.post(()->loading("Recherche indisponible. Réessaie."));}});}
 void loading(String s){content.removeAllViews();content.addView(t(s,15,M));}
 String title(JSONObject x){JSONObject q=x.optJSONObject("title");String s=q==null?"Anime":q.optString("english","");if(s.isEmpty()||s.equals("null"))s=q==null?"Anime":q.optString("romaji","Anime");return s;}
 void render(JSONArray a){content.removeAllViews();if(a.length()==0){content.addView(t("Aucun résultat.",15,M));return;}for(int i=0;i<a.length();i++)card(a.optJSONObject(i));}
 void card(JSONObject x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setPadding(10,10,10,10);c.setBackground(bg(CARD,18));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,6,0,6);ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(im,new LinearLayout.LayoutParams(105,150));JSONObject ci=x.optJSONObject("coverImage");loadImage(ci==null?"":ci.optString("large",""),im);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(12,2,4,2);TextView n=t(title(x),17,W);n.setTypeface(null,1);tx.addView(n);int ep=x.optInt("episodes",0);tx.addView(t((x.optInt("seasonYear",0)>0?x.optInt("seasonYear")+" • ":"")+(ep>0?ep+" épisodes":"en cours"),13,M));tx.addView(t("VF  •  VOSTFR",13,P));tx.addView(t("Ouvrir  ›",14,P));c.addView(tx,new LinearLayout.LayoutParams(0,-1,1));c.setOnClickListener(v->detail(x));content.addView(c,cp);}
 void detail(JSONObject x){selected.clear();ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(18,20,18,54);sc.addView(p);TextView back=t("‹ Accueil",16,P);back.setOnClickListener(v->home());p.addView(back);String name=title(x);TextView h=t(name,27,W);h.setTypeface(null,1);p.addView(h);int total=x.optInt("episodes",0);p.addView(t((total>0?total+" épisodes • ":"")+x.optString("status",""),14,M));
  p.addView(t("Version audio / sous-titres",20,W));LinearLayout lr=new LinearLayout(this);Button vf=btn("VF");Button vo=btn("VOSTFR");lr.addView(vf,new LinearLayout.LayoutParams(0,56,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,56,1);lp.setMargins(8,0,0,0);lr.addView(vo,lp);p.addView(lr);TextView li=t("Choix : "+lang,13,M);p.addView(li);vf.setOnClickListener(v->{lang="VF";li.setText("Choix : VF");});vo.setOnClickListener(v->{lang="VOSTFR";li.setText("Choix : VOSTFR");});
  p.addView(t("Épisodes",22,W));LinearLayout ar=new LinearLayout(this);Button all=btn("Tout sélectionner"),clear=btn("Effacer");ar.addView(all,new LinearLayout.LayoutParams(0,56,1));LinearLayout.LayoutParams cl=new LinearLayout.LayoutParams(0,56,1);cl.setMargins(8,0,0,0);ar.addView(clear,cl);p.addView(ar);LinearLayout eps=new LinearLayout(this);eps.setOrientation(LinearLayout.VERTICAL);p.addView(eps);ArrayList<CheckBox> boxes=new ArrayList<>();int shown=total>0?total:24;for(int i=1;i<=shown;i++){final int no=i;CheckBox cb=new CheckBox(this);cb.setText("Épisode "+i);cb.setTextColor(W);cb.setTextSize(16);cb.setButtonTintList(ColorStateList.valueOf(P));cb.setPadding(8,4,8,4);cb.setOnCheckedChangeListener((b,on)->{if(on)selected.add(no);else selected.remove(no);});boxes.add(cb);eps.addView(cb);}all.setOnClickListener(v->{for(CheckBox b:boxes)b.setChecked(true);});clear.setOnClickListener(v->{for(CheckBox b:boxes)b.setChecked(false);});
  p.addView(t("Qualité",22,W));RadioGroup rg=new RadioGroup(this);final String[] quality={"720p"};for(String q:new String[]{"360p","480p","720p","1080p"}){RadioButton r=new RadioButton(this);r.setText(q);r.setTextColor(W);r.setTextSize(16);r.setButtonTintList(ColorStateList.valueOf(P));if(q.equals("720p"))r.setChecked(true);r.setOnClickListener(v->quality[0]=((RadioButton)v).getText().toString());rg.addView(r,new RadioGroup.LayoutParams(-1,52));}p.addView(rg);Button dl=btn("Télécharger la sélection");LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(-1,64);dp.setMargins(0,14,0,0);p.addView(dl,dp);dl.setOnClickListener(v->{if(selected.isEmpty())Toast.makeText(this,"Sélectionne au moins un épisode",Toast.LENGTH_SHORT).show();else downloads(name,quality[0]);});setContentView(sc);}
 void downloads(String name,String quality){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(18,22,18,50);sc.addView(p);TextView b=t("‹ Accueil",16,P);b.setOnClickListener(v->home());p.addView(b);p.addView(t("Téléchargements",28,W));p.addView(t("Maximum 3 simultanés • "+lang,14,M));int i=0;for(int ep:selected){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(12,10,12,10);row.setBackground(bg(CARD,18));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,6,0,6);row.addView(t(name+" • Épisode "+ep,16,W));row.addView(t(quality+" • "+(i<3?"Préparation":"File d’attente"),13,M));p.addView(row,rp);i++;}p.addView(t("Les sources sont choisies automatiquement. Les connecteurs catalogue prévus incluent Anime-Sama, FRAnime, VoirAnime, VostFree, FSS, HiAnime et MovieBox. La lecture/téléchargement n'utilise que des flux directs compatibles et autorisés.",12,M));setContentView(sc);}
 JSONObject api(String gql,JSONObject vars)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("https://graphql.anilist.co").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","KAZE/5 Android");JSONObject body=new JSONObject().put("query",gql).put("variables",vars==null?new JSONObject():vars);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes("UTF-8"));}InputStream in=c.getResponseCode()<300?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] z=new byte[8192];int n;while((n=in.read(z))>0)out.write(z,0,n);if(c.getResponseCode()>=300)throw new IOException("HTTP "+c.getResponseCode());return new JSONObject(out.toString("UTF-8"));}
 void loadImage(String u,ImageView v){if(u==null||u.isEmpty())return;net.submit(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);Bitmap b=BitmapFactory.decodeStream(c.getInputStream());ui.post(()->v.setImageBitmap(b));}catch(Exception e){}});}
}