package com.mlay.animedownloader;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.content.*;import android.content.res.ColorStateList;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;import org.json.*;
public class MainActivity extends Activity{\n int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
 final int BG=Color.rgb(8,9,15),CARD=Color.rgb(22,24,35),P=Color.rgb(122,69,255),W=Color.WHITE,M=Color.rgb(174,177,195); Handler ui=new Handler(Looper.getMainLooper()); ExecutorService net=Executors.newFixedThreadPool(8); LinearLayout body; EditText query; Set<Integer> selected=new LinkedHashSet<>(); String lang="VOSTFR",quality="720p";
 public void onCreate(Bundle b){super.onCreate(b);home();}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;} TextView tx(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(10),dp(10),dp(10),dp(10));return v;} TextView button(String s){TextView v=tx(s,16,W);v.setGravity(17);v.setTypeface(null,1);v.setBackground(bg(P,26));v.setMinHeight(dp(58));return v;}
 LinearLayout page(String title){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(18),dp(18),dp(100));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));nav(root);if(title!=null){TextView h=tx(title,30,W);h.setTypeface(null,1);body.addView(h);}setContentView(root);return root;}
 void nav(LinearLayout root){LinearLayout n=new LinearLayout(this);String[] a={"⌂\nAccueil","⌕\nRecherche","⇩\nTéléchargements","⚙\nParamètres"};for(String s:a){TextView v=tx(s,12,M);v.setGravity(17);n.addView(v,new LinearLayout.LayoutParams(0,dp(64),1));if(s.startsWith("⌂"))v.setOnClickListener(x->home());if(s.startsWith("⌕"))v.setOnClickListener(x->searchPage());if(s.startsWith("⇩"))v.setOnClickListener(x->downloads());if(s.startsWith("⚙"))v.setOnClickListener(x->settings());}root.addView(n);}
 void home(){page(null);TextView logo=tx("KAZE",36,W);logo.setTypeface(null,1);logo.setGravity(17);body.addView(logo);body.addView(tx("Anime • VF • VOSTFR",13,M));query=new EditText(this);query.setHint("⌕  Rechercher un animé...");query.setHintTextColor(M);query.setTextColor(W);query.setTextSize(17);query.setSingleLine();query.setPadding(18,0,18,0);query.setBackground(bg(CARD,28));body.addView(query,new LinearLayout.LayoutParams(-1,dp(62)));query.setOnEditorActionListener((v,a,e)->{search(query.getText().toString());return true;});chips(new String[]{"Populaire","Récents","Tendance"});section("Animés populaires");catalog("TRENDING_DESC");}
 void section(String s){TextView h=tx(s,22,W);h.setTypeface(null,1);body.addView(h);} void chips(String[] ss){LinearLayout r=new LinearLayout(this);for(String s:ss){TextView v=button(s);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1);p.setMargins(3,4,3,4);r.addView(v,p);}body.addView(r);}
 void searchPage(){page("Recherche");query=new EditText(this);query.setHint("Naruto, One Piece...");query.setHintTextColor(M);query.setTextColor(W);query.setTextSize(18);query.setSingleLine();query.setBackground(bg(CARD,25));query.setPadding(18,0,18,0);body.addView(query,new LinearLayout.LayoutParams(-1,dp(64)));chips(new String[]{"Tous","VF","VOSTFR"});query.setOnEditorActionListener((v,a,e)->{search(query.getText().toString());return true;});}
 void catalog(String sort){body.addView(tx("Chargement...",14,M));net.submit(()->{try{JSONArray a=api("query{Page(page:1,perPage:12){media(type:ANIME,sort:"+sort+",isAdult:false){title{english romaji} coverImage{large} episodes seasonYear status description(asHtml:false)}}} ",null).getJSONObject("data").getJSONObject("Page").getJSONArray("media");ui.post(()->{body.removeViewAt(body.getChildCount()-1);render(a);});}catch(Exception e){ui.post(()->body.addView(tx("Catalogue indisponible.",14,M)));}});}
 void search(String q){q=q.trim().replaceAll("(?i)\\s+(vf|vostfr)$","");if(q.isEmpty())return;body.removeAllViews();section("Résultats");final String z=q;net.submit(()->{try{JSONArray a=api("query($q:String){Page(page:1,perPage:20){media(type:ANIME,search:$q,isAdult:false){title{english romaji} coverImage{large} episodes seasonYear status description(asHtml:false)}}}",new JSONObject().put("q",z)).getJSONObject("data").getJSONObject("Page").getJSONArray("media");ui.post(()->render(a));}catch(Exception e){ui.post(()->body.addView(tx("Recherche indisponible.",14,M)));}});}
 String title(JSONObject x){JSONObject q=x.optJSONObject("title");String s=q.optString("english","");return s.isEmpty()||s.equals("null")?q.optString("romaji","Anime"):s;}
 void render(JSONArray a){for(int i=0;i<a.length();i++)card(a.optJSONObject(i));}
 void card(JSONObject x){LinearLayout c=new LinearLayout(this);c.setPadding(dp(10),dp(10),dp(10),dp(10));c.setBackground(bg(CARD,20));ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(im,new LinearLayout.LayoutParams(dp(105),dp(150)));load(x.optJSONObject("coverImage").optString("large"),im);LinearLayout z=new LinearLayout(this);z.setOrientation(LinearLayout.VERTICAL);z.setPadding(dp(12),0,0,0);TextView n=tx(title(x),18,W);n.setTypeface(null,1);z.addView(n);z.addView(tx(x.optInt("seasonYear")+" • "+x.optInt("episodes")+" épisodes",13,M));z.addView(tx("VF     VOSTFR",13,P));c.addView(z,new LinearLayout.LayoutParams(0,-1,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,6,0,6);body.addView(c,p);c.setOnClickListener(v->detail(x));}
 void detail(JSONObject x){page(null);TextView back=tx("‹ Retour",16,P);back.setOnClickListener(v->home());body.addView(back);section(title(x));int total=x.optInt("episodes",24);body.addView(tx(x.optInt("seasonYear")+" • "+total+" épisodes • "+x.optString("status"),14,M));String d=x.optString("description","");if(!d.isEmpty())body.addView(tx(d.length()>260?d.substring(0,260)+"…":d,14,M));section("Choix de la version");chipsLang();section("Épisodes");ranges(total);episodeList(total,1,Math.min(50,total));}
 void chipsLang(){LinearLayout r=new LinearLayout(this);for(String s:new String[]{"VF (Français)","VOSTFR"}){TextView v=button(s);r.addView(v,new LinearLayout.LayoutParams(0,dp(58),1));v.setOnClickListener(x->{lang=s.startsWith("VF")?"VF":"VOSTFR";Toast.makeText(this,lang,0).show();});}body.addView(r);}
 void ranges(int total){HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout r=new LinearLayout(this);for(int st=1;st<=total;st+=50){int en=Math.min(st+49,total),a=st,b=en;TextView v=button(st+"-"+en);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(120),dp(52));p.setMargins(3,3,3,3);r.addView(v,p);v.setOnClickListener(x->episodeList(total,a,b));}hs.addView(r);body.addView(hs);}
 void episodeList(int total,int st,int en){LinearLayout list=new LinearLayout(this);list.setTag("episodes");list.setOrientation(LinearLayout.VERTICAL);for(int i=st;i<=en;i++){int no=i;CheckBox c=new CheckBox(this);c.setText("Épisode "+i+"                                      ⇩");c.setTextColor(W);c.setTextSize(16);c.setButtonTintList(ColorStateList.valueOf(P));c.setChecked(selected.contains(i));c.setOnCheckedChangeListener((v,on)->{if(on)selected.add(no);else selected.remove(no);});list.addView(c,new LinearLayout.LayoutParams(-1,dp(54)));}body.addView(list);TextView dl=button("Télécharger la sélection ("+selected.size()+")");body.addView(dl,new LinearLayout.LayoutParams(-1,dp(66)));dl.setOnClickListener(v->quality());}
 void quality(){page("Choix qualité");body.addView(tx("Version : "+lang,16,M));section("Choisir la qualité");RadioGroup rg=new RadioGroup(this);for(String q:new String[]{"1080p","720p","480p","360p"}){RadioButton r=new RadioButton(this);r.setText(q);r.setTextColor(W);r.setTextSize(18);r.setButtonTintList(ColorStateList.valueOf(P));r.setChecked(q.equals(quality));r.setOnClickListener(v->quality=q);rg.addView(r,new RadioGroup.LayoutParams(-1,dp(58)));}body.addView(rg);TextView b=button("Démarrer");body.addView(b,new LinearLayout.LayoutParams(-1,66));b.setOnClickListener(v->downloads());}
 void downloads(){page("Téléchargements");chips(new String[]{"En cours","Terminés","Erreurs"});if(selected.isEmpty())body.addView(tx("Aucun téléchargement actif.",15,M));int i=0;for(int ep:selected){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(bg(CARD,18));c.addView(tx("Épisode "+ep+" • "+quality+" • "+lang,17,W));ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress(0);pb.setProgressTintList(ColorStateList.valueOf(P));c.addView(pb);c.addView(tx(i<3?"En attente d’un média HTTP/HLS détecté":"File d’attente",13,M));body.addView(c);i++;}body.addView(tx("Maximum : 3 téléchargements simultanés • 4 connexions par fichier",13,M));}
 void settings(){page("Paramètres");section("Téléchargement");body.addView(tx("Téléchargements simultanés                         3",17,W));body.addView(tx("Connexions par téléchargement                   4",17,W));body.addView(tx("Dossier de destination        Téléchargements/KAZE",16,P));body.addView(tx("☑ Moteur multi-connexions\n☑ Reprendre les téléchargements interrompus\n☑ Créer un dossier par animé\n☑ Séparer VF et VOSTFR",16,W));section("Lecture");body.addView(tx("Lecteur intégré                                      Activé",16,W));}
 JSONObject api(String gql,JSONObject vars)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("https://graphql.anilist.co").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Content-Type","application/json");JSONObject b=new JSONObject().put("query",gql).put("variables",vars==null?new JSONObject():vars);try(OutputStream o=c.getOutputStream()){o.write(b.toString().getBytes("UTF-8"));}InputStream in=c.getResponseCode()<300?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] z=new byte[8192];int n;while((n=in.read(z))>0)out.write(z,0,n);if(c.getResponseCode()>=300)throw new IOException();return new JSONObject(out.toString("UTF-8"));}
 void load(String u,ImageView v){net.submit(()->{try{Bitmap b=BitmapFactory.decodeStream(new URL(u).openStream());ui.post(()->v.setImageBitmap(b));}catch(Exception e){}});}
}