package com.mlay.animedownloader;
import android.app.*;import android.os.*;import android.webkit.*;import android.widget.*;import java.util.*;
public class MediaBrowserActivity extends Activity{
 private LinearLayout found;private WebView web;private final MediaDetector detector=new MediaDetector();private String preferredQuality="720p",preferredLang="SOURCE";private int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 @Override public void onCreate(Bundle b){super.onCreate(b);preferredQuality=getIntent().getStringExtra("quality");if(preferredQuality==null)preferredQuality="720p";preferredLang=getIntent().getStringExtra("lang");if(preferredLang==null)preferredLang="SOURCE";LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xff08090f);EditText address=new EditText(this);address.setHint("Adresse d’une page autorisée");address.setSingleLine();address.setTextColor(0xffffffff);address.setHintTextColor(0xffaaaec0);root.addView(address,new LinearLayout.LayoutParams(-1,dp(56)));found=new LinearLayout(this);found.setOrientation(LinearLayout.VERTICAL);root.addView(found);web=new WebView(this);WebSettings w=web.getSettings();w.setJavaScriptEnabled(true);w.setDomStorageEnabled(true);w.setMediaPlaybackRequiresUserGesture(false);web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(detector.client((url,type,headers)->runOnUiThread(()->add(url,type,headers))));root.addView(web,new LinearLayout.LayoutParams(-1,0,1));address.setOnEditorActionListener((v,a,e)->{String u=address.getText().toString().trim();if(!u.startsWith("http"))u="https://"+u;web.loadUrl(u);return true;});setContentView(root);}
 private void add(String url,String type,Map<String,String> requestHeaders){Button b=new Button(this);b.setAllCaps(false);b.setText(type+" détecté • Télécharger");b.setOnClickListener(v->{Map<String,String> h=new HashMap<>(requestHeaders);String cookie=CookieManager.getInstance().getCookie(url);if(cookie!=null&&!cookie.isEmpty())h.put("Cookie",cookie);h.put("User-Agent",web.getSettings().getUserAgentString());if(!h.containsKey("Referer"))h.put("Referer",web.getUrl()==null?"":web.getUrl());if("HLS".equals(type)){inspectHls(url,h);}else{enqueue(url,type,h,preferredQuality);}});found.addView(b,new LinearLayout.LayoutParams(-1,dp(60)));}
 private void inspectHls(String url,Map<String,String> h){new Thread(()->{try{java.net.HttpURLConnection c=(java.net.HttpURLConnection)new java.net.URL(url).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(20000);for(Map.Entry<String,String> e:h.entrySet())if(e.getKey()!=null&&e.getValue()!=null&&!e.getValue().isEmpty())c.setRequestProperty(e.getKey(),e.getValue());java.io.ByteArrayOutputStream o=new java.io.ByteArrayOutputStream();try(java.io.InputStream in=c.getInputStream()){byte[] z=new byte[8192];int n;while((n=in.read(z))!=-1)o.write(z,0,n);}String m=o.toString("UTF-8");c.disconnect();ArrayList<String> qs=new ArrayList<>();for(String line:m.split("\\r?\\n"))if(line.startsWith("#EXT-X-STREAM-INF")){int p=line.indexOf("RESOLUTION=");if(p>=0){String x=line.substring(p+11).split(",")[0];int k=x.indexOf('x');if(k>=0){String q=x.substring(k+1).replaceAll("[^0-9]","")+"p";if(!q.equals("p")&&!qs.contains(q))qs.add(q);}}}runOnUiThread(()->{if(qs.isEmpty())enqueue(url,"HLS",h,"AUTO");else showQualities(url,"HLS",h,qs);});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Analyse HLS impossible : "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
 private void showQualities(String url,String type,Map<String,String> h,List<String> available){String[] qs=available.toArray(new String[0]);int checked=0;for(int i=0;i<qs.length;i++)if(qs[i].equals(preferredQuality))checked=i;final int initial=checked;new AlertDialog.Builder(this).setTitle("Qualités réellement disponibles").setSingleChoiceItems(qs,initial,null).setPositiveButton("Télécharger",(d,w)->{int pos=((AlertDialog)d).getListView().getCheckedItemPosition();enqueue(url,type,h,qs[pos<0?initial:pos]);}).setNegativeButton("Annuler",null).show();}
 private void enqueue(String url,String type,Map<String,String> h,String q){String ext="WEBM".equals(type)?".webm":"HLS".equals(type)?"":".mp4";DownloadQueue.add(this,url,"Média détecté",preferredLang,"kaze_"+System.currentTimeMillis()+ext,h,type,q);Toast.makeText(this,"Téléchargement ajouté • "+q+" • "+preferredLang,Toast.LENGTH_SHORT).show();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}
